name: Run tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.7.2"
    - uses: actions/checkout@v3
    - name: Run tests
      run: swift test -v
